defByLevel = 2
atkByLevel = 2
reduceMoveByPoison = 1
bonusAtkByWispAura = 10
reduceAtkPoison = 10
reduceDefPoison = 10
bonusAtkByWater = 10
bonusDefByWater = 15
levelList = [0, 84, 172, 265, 362, 464, 571, 684, 802, 926]
commanderList = ['galamar', 'valadorn', 'demon-lord', 'saeth']
commanderAddedCost = 200
defaultHealth = 100
prototypes = {
    'galamar': {
        'name': 'Galamar',
        'description': 'Galamar (commander) is very strong in attack and defence. Commanders can also occupy castles to produce troops and can be revived in the castle if they fall in battle.',
        'atk': {'min': 55, 'max': 65},
        'atkRange': 1,
        'def': 20,
        'mov': 4,
        'canFixBuilding': True,
        'withoutGrave': True,
        'canOccupyBuilding': ['farm', 'castle'],
        'cost': 200,
    },
    'valadorn': {
        'name': 'Valadorn',
        'description': 'Valadorn (commander) is very strong in attack and defence. Commanders can also occupy castles to produce troops and can be revived in the castle if they fall in battle.',
        'atk': {'min': 55, 'max': 65},
        'atkRange': 1,
        'def': 20,
        'mov': 4,
        'canFixBuilding': True,
        'withoutGrave': True,
        'canOccupyBuilding': ['farm', 'castle'],
        'cost': 200,
    },
    'demon-lord': {
        'name': 'Demon Lord',
        'description': 'Demon Lords (commander) is very strong in attack and defence. Commanders can also occupy castles to produce troops and can be revived in the castle if they fall in battle.',
        'atk': {'min': 55, 'max': 65},
        'atkRange': 1,
        'def': 20,
        'mov': 4,
        'canFixBuilding': True,
        'withoutGrave': True,
        'canOccupyBuilding': ['farm', 'castle'],
        'cost': 200,
    },
    'saeth': {
        'name': 'Saeth',
        'description': 'Saeth (commander) is very strong in attack and defence. Commanders can also occupy castles to produce troops and can be revived in the castle if they fall in battle.',
        'atk': {'min': 55, 'max': 65},
        'atkRange': 1,
        'def': 20,
        'mov': 4,
        'canFixBuilding': True,
        'withoutGrave': True,
        'canOccupyBuilding': ['farm', 'castle'],
        'cost': 200,
    },
    'saeth-heavens-fury': {
        'name': 'Saeth',
        'description': 'Saeth (commander) is very strong in attack and defence. Commanders can also occupy castles to produce troops and can be revived in the castle if they fall in battle.',
        'atk': {'min': 55, 'max': 65},
        'atkRange': 15,
        'def': 45,
        'mov': 0,
        'cost': 0,
    },
    'soldier': {
        'name': 'Soldier',
        'description': 'Soldiers are solid all-round fighters that form the backbone of any army. Soldiers are also the only unit that can capture towns to earn gold.',
        'atk': {'min': 50, 'max': 55},
        'atkRange': 1,
        'def': 5,
        'mov': 4,
        'canFixBuilding': True,
        'canOccupyBuilding': ['farm'],
        'cost': 150,
    },
    'archer': {
        'name': 'Archer',
        'description': 'With their powerful bows archers can attack from a distance and are especially powerful against airborne enemies.',
        'atk': {'min': 50, 'max': 55},
        'atkRange': 2,
        'def': 5,
        'mov': 4,
        'bonusAtkAgainstFly': 30,
        'cost': 250,
    },
    'elemental': {
        'name': 'Elemental',
        'description': 'Elementals are magical water spirits. When in water, Elementals have greater movement and stronger defence.',
        'atk': {'min': 50, 'max': 55},
        'atkRange': 1,
        'def': 10,
        'mov': 4,
        'moveType': 'flow',
        'cost': 300,
    },
    'sorceress': {
        'name': 'Sorceress',
        'description': 'Skilled in the use of magic, Sorceresses are weak in close combat. However, their ability to summon fighting skeletons from dead troops can be decisive in battle.',
        'atk': {'min': 40, 'max': 45},
        'atkRange': 1,
        'raiseRange': 2,
        'def': 5,
        'mov': 4,
        'cost': 400,
    },
    'wisp': {
        'name': 'Wisp',
        'description': 'These mystical beings of pure light radiate an aura which strengthens the attacking abilities of nearby friendly units. In close combat they are especially deadly against skeletons.',
        'atk': {'min': 35, 'max': 40},
        'atkRange': 1,
        'auraRange': 3,
        'def': 10,
        'mov': 4,
        'bonusAtkAgainstSkeleton': 30,
        'cost': 500,
    },
    'dire-wolf': {
        'name': 'Dire wolf',
        'description': 'Dire Wolves are feared hunters that travel in packs. Beware - their bite is poisonous and reduces both attack and defence levels for one turn.',
        'atk': {'min': 60, 'max': 65},
        'atkRange': 1,
        'def': 15,
        'mov': 5,
        'poisonPeriod': 2,
        'cost': 600,
    },
    'golem': {
        'name': 'Golem',
        'description': 'Golems are ancient beings - slow but immensely strong in defence. A golem stationed in a building or a well defended mountain is very difficult to defeat.',
        'atk': {'min': 60, 'max': 70},
        'atkRange': 1,
        'def': 30,
        'mov': 4,
        'cost': 600,
    },
    'catapult': {
        'name': 'Catapult',
        'description': 'Catapults blaze a trail of destruction with their enormous attack range. However, their relative immobility and inability to attack up close make them vulnerable, so guard them well. Catapults can either move or attack during a turn, but not do both.',
        'atk': {'min': 50, 'max': 70},
        'atkRange': {'min': 2, 'max': 4},
        'def': 10,
        'mov': 3,
        'cost': 700,
        'cannotActAfterMove': True,
        'canDestroyBuilding': True,
    },
    'dragon': {
        'name': 'Dragon',
        'description': 'These massive flying beasts have ruled over the mountains of mist since ancient times. They are extremely mobile as well as deadly in attack on land, air and sea.',
        'atk': {'min': 70, 'max': 80},
        'atkRange': 1,
        'def': 25,
        'mov': 6,
        'moveType': 'fly',
        'cost': 1000,
    },
    'skeleton': {
        'name': 'Skeleton',
        'description': 'Summoned by Sorceresses, these lifeless warriors are as strong as soldiers and deadly opponents on any battlefield.',
        'atk': {'min': 40, 'max': 50},
        'atkRange': 1,
        'def': 2,
        'mov': 4,
        'withoutGrave': True,
        'cost': 0,
    },
    'crystal': {
        'name': 'Crystal',
        'description': 'These legendary Crystals were originally retrieved from the ruins of the Ancient Citadel. Little is known of their power, except that they are rumoured to protect the kingdom, while also possessing the power to destroy it.',
        'atk': {'min': 0, 'max': 0},
        'atkRange': 0,
        'def': 15,
        'mov': 3,
        'cost': 0,
    },
}
